2023-11-17 19:20:08,388:ERROR: 
An exception has occured on epoch 2:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:20:19,111:ERROR: 
An exception has occured on epoch 3:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:20:31,075:ERROR: 
An exception has occured on epoch 4:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:20:42,667:ERROR: 
An exception has occured on epoch 5:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:21:02,496:ERROR: 
An exception has occured on epoch 7:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:21:22,720:ERROR: 
An exception has occured on epoch 9:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:21:43,277:ERROR: 
An exception has occured on epoch 11:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:22:02,356:ERROR: 
An exception has occured on epoch 13:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 124, in train
    params = json.dumps(params)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/eduardoleao/miniconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2023-11-17 19:22:52,226:INFO: 
Loading data...
2023-11-17 19:22:55,294:INFO: 
Building model...
2023-11-17 19:22:55,296:INFO: 
Training model...
2023-11-17 19:23:02,335:ERROR: 
An exception has occured on epoch 0:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 126, in train
    file = open(self.args.to_file, 'w')
                ^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'to_file'
2023-11-17 19:23:19,730:ERROR: 
An exception has occured on epoch 2:
Traceback (most recent call last):
  File "/Users/eduardoleao/Documents/ML/NN/cnn/model.py", line 126, in train
    file = open(self.args.to_file, 'w')
                ^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'to_file'
2023-11-17 19:23:56,011:INFO: 
Loading data...
2023-11-17 19:23:58,706:INFO: 
Building model...
2023-11-17 19:23:58,709:INFO: 
Training model...
2023-11-17 20:03:11,314:INFO: 
Loading data...
2023-11-17 20:03:13,891:INFO: 
Building model...
2023-11-17 20:03:13,895:INFO: 
Training model...
2023-11-17 20:07:44,738:INFO: 
Loading data...
2023-11-17 20:07:47,601:INFO: 
Building model...
2023-11-17 20:07:47,605:INFO: 
Training model...
2023-11-17 20:08:06,403:INFO: 
Loading data...
2023-11-17 20:08:09,145:INFO: 
Building model...
2023-11-17 20:08:09,148:INFO: 
Training model...
2023-11-17 20:09:21,319:INFO: 
Loading data...
2023-11-17 20:09:24,886:INFO: 
Building model...
2023-11-17 20:09:24,889:INFO: 
Training model...
2023-11-17 20:11:23,456:INFO: 
Loading data...
2023-11-17 20:11:23,977:INFO: 
Building model...
2023-11-17 20:11:23,978:INFO: \Testing model...
2023-11-17 20:12:55,012:INFO: 
Loading data...
2023-11-17 20:12:55,377:INFO: 
Building model...
2023-11-17 20:12:55,379:INFO: \Testing model...
2023-11-17 20:14:05,665:INFO: 
Loading data...
2023-11-17 20:14:06,022:INFO: 
Building model...
2023-11-17 20:14:06,023:INFO: \Testing model...
2023-11-17 20:14:28,332:INFO: 
Loading data...
2023-11-17 20:14:31,342:INFO: 
Building model...
2023-11-17 20:14:31,345:INFO: 
Training model...
2023-11-17 20:16:04,000:INFO: 
Loading data...
2023-11-17 20:16:06,572:INFO: 
Building model...
2023-11-17 20:16:06,575:INFO: 
Training model...
2023-11-17 20:16:41,511:INFO: 
Loading data...
2023-11-17 20:16:44,421:INFO: 
Building model...
2023-11-17 20:16:44,424:INFO: 
Training model...
2023-11-17 20:18:17,101:INFO: 
Loading data...
2023-11-17 20:18:17,462:INFO: 
Building model...
2023-11-17 20:18:17,463:INFO: \Testing model...
2023-11-17 20:21:36,501:INFO: 
Loading data...
2023-11-17 20:21:39,077:INFO: 
Building model...
2023-11-17 20:21:39,078:INFO: 
Training model...
2023-11-17 20:25:22,637:INFO: 
Loading data...
2023-11-17 20:25:25,272:INFO: 
Building model...
2023-11-17 20:25:25,275:INFO: 
Training model...
2023-11-17 20:27:23,542:INFO: 
Loading data...
2023-11-17 20:27:23,910:INFO: 
Building model...
2023-11-17 20:27:23,911:INFO: \Testing model...
2023-11-17 20:28:28,805:INFO: 
Loading data...
2023-11-17 20:28:29,185:INFO: 
Building model...
2023-11-17 20:28:29,187:INFO: \Testing model...
2023-11-17 20:29:19,685:INFO: 
Loading data...
2023-11-17 20:29:20,047:INFO: 
Building model...
2023-11-17 20:29:38,893:INFO: 
Loading data...
2023-11-17 20:29:39,253:INFO: 
Building model...
2023-11-17 20:29:39,254:INFO: \Testing model...
2023-11-17 20:31:31,804:INFO: 
Loading data...
2023-11-17 20:31:32,165:INFO: 
Building model...
2023-11-17 20:31:32,166:INFO: \Testing model...
2023-11-17 20:31:41,056:INFO: 
Loading data...
2023-11-17 20:31:44,087:INFO: 
Building model...
2023-11-17 20:31:44,089:INFO: 
Training model...
2023-11-17 20:32:14,681:INFO: 
Loading data...
2023-11-17 20:32:17,440:INFO: 
Building model...
2023-11-17 20:32:17,443:INFO: 
Training model...
2023-11-17 20:33:10,685:INFO: 
Loading data...
2023-11-17 20:33:13,278:INFO: 
Building model...
2023-11-17 20:33:13,281:INFO: 
Training model...
2023-11-17 20:34:50,152:INFO: 
Loading data...
2023-11-17 20:34:52,886:INFO: 
Building model...
2023-11-17 20:34:52,888:INFO: 
Training model...
2023-11-17 20:35:11,696:INFO: 
Loading data...
2023-11-17 20:35:14,356:INFO: 
Building model...
2023-11-17 20:35:14,358:INFO: 
Training model...
2023-11-17 20:36:49,095:INFO: 
Loading data...
2023-11-17 20:36:52,059:INFO: 
Building model...
2023-11-17 20:36:52,063:INFO: 
Training model...
2023-11-17 20:38:41,907:INFO: 
Loading data...
2023-11-17 20:38:44,669:INFO: 
Building model...
2023-11-17 20:38:44,671:INFO: 
Training model...
2023-11-17 20:40:08,925:INFO: 
Loading data...
2023-11-17 20:40:11,530:INFO: 
Building model...
2023-11-17 20:40:11,532:INFO: 
Training model...
2023-11-17 20:41:43,698:INFO: 
Loading data...
2023-11-17 20:41:46,307:INFO: 
Building model...
2023-11-17 20:41:46,311:INFO: 
Training model...
2023-11-17 20:43:38,043:INFO: 
Loading data...
2023-11-17 20:43:40,949:INFO: 
Building model...
2023-11-17 20:43:40,952:INFO: 
Training model...
2023-11-17 20:45:06,719:INFO: 
Loading data...
2023-11-17 20:45:07,092:INFO: 
Building model...
2023-11-17 20:45:07,093:INFO: \Testing model...
2023-11-17 20:45:58,280:INFO: 
Loading data...
2023-11-17 20:45:58,664:INFO: 
Building model...
2023-11-17 20:45:58,666:INFO: \Testing model...
2023-11-17 20:46:32,726:INFO: 
Loading data...
2023-11-17 20:46:33,095:INFO: 
Building model...
2023-11-17 20:46:55,658:INFO: 
Loading data...
2023-11-17 20:46:56,026:INFO: 
Building model...
2023-11-17 20:46:56,027:INFO: \Testing model...
2023-11-17 20:47:28,985:INFO: 
Loading data...
2023-11-17 20:47:29,360:INFO: 
Building model...
2023-11-17 20:47:29,362:INFO: \Testing model...
2023-11-17 20:48:47,028:INFO: 
Loading data...
2023-11-17 20:48:47,401:INFO: 
Building model...
2023-11-17 20:48:47,403:INFO: \Testing model...
2023-11-17 20:51:10,124:INFO: 
Loading data...
2023-11-17 20:51:13,255:INFO: 
Building model...
2023-11-17 20:51:13,258:INFO: 
Training model...
2023-11-17 20:53:58,439:INFO: 
Loading data...
2023-11-17 20:53:59,153:INFO: 
Building model...
2023-11-17 20:53:59,154:INFO: \Testing model...
2023-11-17 20:55:21,881:INFO: 
Loading data...
2023-11-17 20:55:25,351:INFO: 
Building model...
2023-11-17 20:55:25,354:INFO: 
Training model...
